name: iOS Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-14
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Run Tests
        run: |
          cd XKCDViewer
          xcodebuild test \
            -project XKCDViewer.xcodeproj \
            -scheme XKCDViewer \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            -only-testing:XKCDViewerTests \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO 